### ISSUE TITLE
Blank screen when used a particular website. 

### ISSUE THREAD

**Issue by TimotheeJeannin** [cliqz-oss/adblocker#1721] opened 2021-03-01 13:28 UTC
Hi @remusao, 

If I use puppeteer with an adblocker to capture a screenshot of https://www.bloomandwild.com/send-flowers/send/the-sam/3611 the website is a blank page. I searched which rule could be causing this but could not find any. What is quite strange is that, if I remove all the rules and load the adblocker without any rule, the website is still blank. Any idea what could be causing this? 

Have a good day ! 

Tim

**Comment by remusao** [comment] 2021-03-02 09:29
Hi @TimotheeJeannin,

I had a quick look and could not see what is wrong with the blocking, it seems to be similar to what happens in a browser. Unfortunately I am busy with some other projects at the moment so I am not sure I can investigate deeper this in the immediate future. I'm happy to assist in whatever capacity I can if you want to look into it. If it also happens even without any rule, it would be interesting to see if it's enough to register some puppeteer listeners to trigger the issue (e.g. maybe check if enabling request interception and adding the listeners there breaks the site somehow? https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L76).

Best,
Rémi

**Comment by TimotheeJeannin** [comment] 2021-03-03 08:33
Hi @remusao, 

I made a few tests and it looks like enabling request interception is what's causing the website to break.
There may be a race condition somewhere. I will get back to you if I find something.

Best, 
Timothée

**Comment by remusao** [comment] 2021-05-03 20:29
Hey @TimotheeJeannin,

Did you manage to find the root cause of the issue you encountered? I would be curious to know if this was caused by some kind of bug in puppeteer or something related to the adblocker?

Best,

**Comment by TimotheeJeannin** [comment] 2021-05-04 07:33
Hi @remusao.

Unfortunately I did not found the root cause of the issue, but if I remember correctly, I don't think it's related caused by the adblocker.

Best,

**Comment by remusao** [comment] 2021-05-04 07:54
Thanks for coming back. I will be closing this issue if that's fine. Feel free to reopen or create a new issue if you need anything else.

**Closed by remusao** 2021-05-04 07:54 UTC
