### ISSUE TITLE
Cosmetic filtering doesn't work in Electron

### ISSUE THREAD

**Issue by sentialx** [cliqz-oss/adblocker#354] opened 2019-09-27 11:42 UTC
Hi, I noticed when going to http://raymondhill.net/ublock/tiles1.html and http://raymondhill.net/ublock/adbox.html it doesn't block the elements in Wexond. 

![image](https://user-images.githubusercontent.com/11065386/65766924-a7b55400-e12c-11e9-8633-3c4878331ecf.png)

![image](https://user-images.githubusercontent.com/11065386/65766942-b13ebc00-e12c-11e9-9dc4-00c8d78058ed.png)

**Comment by remusao** [comment] 2019-09-28 09:13
Hi @sentialx,

I will check this out. It's weird because in `adblocker-electron-example` cosmetics seem to be working fine. Maybe something is conflicting with Wexond somehow.

Rémi

**Comment by remusao** [comment] 2019-09-30 15:29
@sentialx I've made a fix for this in https://github.com/cliqz-oss/adblocker/pull/358

The issue is that we did not handle injection properly for initial DOM nodes (when the `DOMContentLoaded` event is fired). Now it works better! There is still an issue remaining though as in some cases the custom style will not be able to override CSS declared as `!important` in the page; but this is a limitation of Electron unfortunately. I do not expect this case to be so common though.

**Comment by sentialx** [comment] 2019-09-30 15:54
@remusao So I have good news for you. I created an issue regarding the `cssOrigin` option https://github.com/electron/electron/issues/19256 (because I also tried to support uBlock Origin in my own [WebExtensions implementation](https://github.com/sentialx/electron-extensions)) and the feature shipped with `7.0.0-beta` release.

**Comment by remusao** [comment] 2019-09-30 15:56
This is great! Let's add it as an option as soon as `electron` v7 lands. Or do you think we could add the option now and it will be ignored on v6?

**Comment by sentialx** [comment] 2019-09-30 15:59
@remusao I think it will be ignored (only TypeScript could throw errors, but that's not a problem)

**Comment by remusao** [comment] 2019-09-30 16:08
@sentialx I tried locally with latest Electron beta but could not make it work. I suggest to merge the current fix as is and I will create another issue to think about updating the code to new API once Electron v7 hits the registry!

**Comment by remusao** [comment] 2019-09-30 16:10
Thanks @sentialx! I will try to release a new version of the adblocker tomorrow (since there are a few things in the changelog I need to perform some additional testing to make sure everything works fine).

**Closed** 2019-09-30 16:09 UTC
Labels: investigation needed

**Comment by remusao** [comment] 2019-10-01 13:22
@sentialx => https://github.com/cliqz-oss/adblocker/releases/tag/v1.2.0
