### ISSUE TITLE
Some websites just don't load

### ISSUE THREAD

**Issue by sentialx** [cliqz-oss/adblocker#311] opened 2019-09-02 15:44 UTC
Hi, I noticed (and also others noticed, see https://github.com/wexond/desktop/issues/320) that some websites don't load. I've discovered only 2 websites which don't work: 
- http://mixpanel.com/
- http://raymondhill.net/ublock/adbox.html/

After disabling adblock, these two are loading properly.

**Comment by remusao** [comment] 2019-09-02 16:24
Hi @sentialx,

I could reproduce locally and pushed a fix there https://github.com/cliqz-oss/adblocker/pull/312. The issue is that some filters can apply on the main document request, which then prevents the website from loading completely. I've added a check to prevent that from happening.

I will release a minor release today.

**Closed** 2019-09-02 16:40 UTC

**Comment by sentialx** [comment] 2019-09-02 16:50
Thanks!

**Comment by remusao** [comment] 2019-09-02 16:50
No worries. Release `v1.0.2` fixing this issue is already available.
