### ISSUE TITLE
clarin.com is broken with Ghostery enabled

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/adblocker#457] opened 2020-02-05 13:01 UTC
Comments are not working on news articles on this website, for example

https://www.clarin.com/politica/emmanuel-macron-alberto-fernandez-francia-acompanara-movilizara-fmi-ayudar-argentina-_0_4kNJxyBG.html

Screenshot:

![Captura de Pantalla 2020-02-05 a la(s) 10 01 27](https://user-images.githubusercontent.com/57176665/73844011-7d705300-47fe-11ea-9281-0cb1fe51d16a.png)

**Comment by remusao** [comment] 2020-02-05 13:39
This does not seem to be caused by the adblocker. Can you maybe check which individual domains are blocked in Ghostery? I suspect that one of them might be causing the breaking. I suspect that `gigya` might be the culprit. If you whitelist it, are the comments working correctly?

**Comment by Lucas-Di-Tomase** [comment] 2020-02-05 13:47
You are correct! Whitelisting gigya solves the problem :)

**Comment by Lucas-Di-Tomase** [comment] 2020-02-05 13:48
Should that be added as an exception to Ghostery by default? (even though is listed under site statistics)

**Comment by Lucas-Di-Tomase** [comment] 2020-02-05 13:49
![Captura de Pantalla 2020-02-05 a la(s) 10 48 56](https://user-images.githubusercontent.com/57176665/73847478-20c46680-4805-11ea-9262-f51ebdee8ecc.png)

**Comment by remusao** [comment] 2020-02-05 14:29
@Lucas-Di-Tomase yes indeed. I have forwarded this issue internally to the person in charge of the tracking database, we might need to fine-tine the behavior for this `gigya` domain. Thanks a lot for double-checking!

**Comment by remusao** [comment] 2020-03-28 11:50
Closing this for now as it does not depend on the adblocker library. If the issue persists, let's re-open an issue on the ghostery-extension repository instead. Thanks again for your help!

**Closed by remusao** 2020-03-28 11:50 UTC
